Plug 'kana/vim-textobj-user'
Plug 'kana/vim-textobj-line'
Plug 'kana/vim-textobj-entire'
Plug 'kana/vim-textobj-indent'
Plug 'inside/vim-textobj-jsxattr'
Plug 'rhysd/vim-textobj-anyblock'
Plug 'kana/vim-textobj-function'
Plug 'haya14busa/vim-textobj-function-syntax'
Plug 'vim-scripts/argtextobj.vim'

Plug 'Chun-Yang/vim-textobj-chunk'
